### PR TITLE
Atmosphere model

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Wanted to merge this, since SimpleAC uses this. Also it's an interesting example of a fast signomial equality (because it is really well approximated as a monomial.)

### CODE REVIEW

**Comment by bqpd** [comment]
add to whitelist

**Comment by bqpd** [comment]
test this please

**Comment by 1ozturkbe** [comment]
So, there are fits for every atmospheric variable, but not all of them are relevant to every problem, and they will not be bounded for every problem either. So I was thinking that people could repurpose these as they see fit.

**Comment by bqpd** [comment]
Sounds great! Maybe put that in a comment or docstring?

**Comment by 1ozturkbe** [comment]
I thought I made that clear in the docstring, but maybe I can make it better!

**Comment by 1ozturkbe** [comment]
Good! Merging.

**Pull request merged**
