### PR TITLE
Adding .pdfs missing in README. 

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Quick fixes to uncompiled READMEs.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
@mjburton11 There are compile errors in wing and empennage models within the GP section. Please fix, should be pretty straightforward.

**Comment by 1ozturkbe** [comment]
There are also some missing pdf's in the SP section. This is not urgent but would be great if completed.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Pull request merged**
