### PR TITLE
allow for beam model to modify loading distribution, shear and moment calculations

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
@bqpd so, very strange, but apparently the windows version of `numpy` doesn't have `flip`...

**Comment by bqpd** [comment]
@galbramc could we update the numpy version on Windows 10 to 1.12? Currently it is 1.11.3 : https://acdl.mit.edu/csi/job/gpkit_commons_PR_Models/buildnode=windows10x64,optimizer=mosek/40/consoleFull

**Comment by galbramc** [comment]
So are you bumping up your minimum numpy version requirement? Have you updated the setup.py (I think that's where it's listed).

**Comment by bqpd** [comment]
Hmm, that raises the question of what we should do with dependency tests and gplibrary...for now I'm tempted to do just as you say and bump up the numpy requirement in https://github.com/convexengineering/gplibrary/blob/master/setup.py, and say that gplibrary has more stringent requirements than gpkit

**Comment by bqpd** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
@bqpd it looks like SP aircraft is failing on windows?

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Pull request merged**
