### PR TITLE
Vectorized SP Atmosphere Model

### PR DESCRIPTION
**Pull request by mayork**
Working to develop a vectorized SP atmosphere model that can be integrated with the flight profile code

### CODE REVIEW

**Comment by mayork** [comment]
@1ozturkbe this is the SP atmosphere model I showed you that has the weird behavior. In addition to developing  a working SP atmosphere model we should figure out why the SP approximations prevent this model from solving to thy physically meaningful atmosphere we're trying to model

**Comment by whoburg** [comment]
Hey @bqpd, do you think we should give `ConstraintSet` a `.vectorize(N, exclude=None)` method that turns all variables into VectorVariables of length N except for the exclude set?

This design pattern seems like it might show up a lot. A model like atmosphere does not involve vectors itself, but needs to be vectorized to evaluate performance across a vector of heights, for example.

What's interesting is if the ConstraintSet already has VectorVariables not in exclude -- these would probably be promoted to matrices?

**Comment by bqpd** [comment]
Hmm! I like that syntax. Gonna be a little messy to make...

**Comment by whoburg** [comment]
This should be updated -- VectorVariables can be removed now that we have http://gpkit.readthedocs.io/en/latest/modelbuilding.html#vectorization

**Comment by mayork** [comment]
I'll replace the file with what I'm using for D8

**Comment by bqpd** [comment]
Awesome!

**Comment by 1ozturkbe** [comment]
This is suuuuper deprecated. Let me make another issue for it.

**Pull request closed without merging**
