### PR TITLE
explicitly add wing interior to v-h tails

### PR DESCRIPTION
**Pull request by mjburton11**
redefine fillModel in htail and vtail models

### CODE REVIEW

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
@galbramc @bqpd after some investigation, I believe when this run tests it's tests it is testing the research repos by checking out the gpkitmodels branch that is specified in each TESTCONFIG file.  What is should do is check out the branch of the PR.  The last push I did, ran all the test successfully in the PR but then once I pushed all of the research repos started failing for that reason.

**Comment by bqpd** [comment]
oops yes I can see how that happened. will fix tomorrow.

**Comment by mjburton11** [comment]
Great.  This might allow us to stop specifying the gpkitmodels branch on TESTCONFIG and just always test on master.

**Comment by mjburton11** [comment]
@bqpd ping

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
teset models please

**Comment by mjburton11** [comment]
@bqpd what the heck, why is turbofan failing? and only on mac?

**Comment by bqpd** [comment]
>:(

**Comment by bqpd** [comment]
looking into it

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
Now it passes. ? ? ?

**Pull request merged**
