### PR TITLE
delete lam as input to wing setup for tails

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
test models please

**Comment by mjburton11** [comment]
@bqpd hey can you change the testing script so that it tests the repos from this branch?

**Comment by mjburton11** [comment]
@bqpd ping

**Comment by bqpd** [comment]
waiting on https://github.com/convexengineering/gpkit/pull/1187

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by mjburton11** [comment]
@bqpd do you know why this is failing?

**Comment by bqpd** [comment]
still working on the backend over in https://github.com/convexengineering/gpkit/pull/1188

**Comment by mjburton11** [comment]
ah ok sorry

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mjburton11 I think it's working now

**Comment by mjburton11** [comment]
it looks like it's having trouble building the jho repo?

**Comment by bqpd** [comment]
where are you seeing that? it's failing on gassolar...

**Comment by mjburton11** [comment]
oops, I was looking at an older failed build.  yeah it seems like gassolar is not installing correctly??

**Comment by mjburton11** [comment]
@bqpd it looks like it's not testing the `solar` repo?

**Comment by bqpd** [comment]
solar is not in https://github.com/convexengineering/gplibrary/blob/master/EXTERNALTESTS

**Comment by mjburton11** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Pull request merged**
