### PR TITLE
update bounds

### PR DESCRIPTION
**Pull request by bqpd**
preparation for https://github.com/convexengineering/gpkit/pull/1238

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mjburton11 please review

**Comment by bqpd** [comment]
Merging to pass model tests on the gpkit PR

**Comment by mjburton11** [comment]
@bqpd @nillst Ned.... `Constants` is not creating variables in `CFRPFabric` in `gpkitmodels.GP.materials.composite`.  Also, looks like this had not passed tests before merging... not cool.

**Comment by bqpd** [comment]
Are you on the newest version of gpkit? It wouldn't have passed tests because the new gpkit hadn't been merged yet :( chicken and egg problem

**Comment by bqpd** [comment]
it passes tests now though!

**Pull request merged**
