### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by 1ozturkbe**

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
test models please

**Comment by 1ozturkbe** [comment]
test models please

**Comment by 1ozturkbe** [comment]
@bqpd what do we do since model tests fail? I would like to merge this ASAP since tests run on master, and I need parts of gplibrary for robust. Lmk.

**Comment by bqpd** [comment]
@1ozturkbe model tests need to pass before you merge onto gplibrary...they're a lot of what actually tests gplibrary's functionality!

The error seems to have been in the converter's use of `from __future__ import absolute_import`. The latest commit removes it and makes the commits local where necessary.

**Comment by bqpd** [comment]
oops, forget to check it still worked with python 3...latest commit fixes that.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by 1ozturkbe** [comment]
Ready to merge after review!

**Pull request merged**
