### PR TITLE
SimPleAC

### PR DESCRIPTION
**Pull request by 1ozturkbe**
This is waiting for the atmos PR, but wanted to put this on the radar.

### CODE REVIEW

**Comment by bqpd** [comment]
Want to add this to the testing?

**Comment by 1ozturkbe** [comment]
Yes, let me do that.

**Comment by bqpd** [comment]
@1ozturkbe the tests appear to not be passing.

**Comment by 1ozturkbe** [comment]
Will take a look now.

**Comment by 1ozturkbe** [comment]
This will need both the SP atmosphere model from latest gplibrary master, and the merge of the relaxed_constants heuristic into gpkit. Getting both done now.

**Comment by 1ozturkbe** [comment]
test models please.

**Pull request merged**
