### PR TITLE
SimPleAC update. 

### PR DESCRIPTION
**Pull request by 1ozturkbe**
This adds revisions for integration with robust testing (so we can remove gassolar from the requirements, as it is no longer being kept up to date).

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
Arg, I thought this was going to be an easy merge, but it seems like a variable ('C_m') is unbounded only when solving with cvxopt. I tried adding a dummy lower bound to the problem although C_m has a substitution, but this didn't fix the issue. I am traveling this weekend, but can look more in detail on Monday. In the meanwhile, if you have any insights @bqpd they would be appreciated.

**Comment by 1ozturkbe** [comment]
@bqpd looked at this again, and don't see any reason why the cvxopt solves should give unbounded, esp since mosek solves the problems fine. Is it possible to put a skipsolvers for the SPaircraft models in tests?

**Comment by 1ozturkbe** [comment]
@bqpd this is important for getting documentation up for robust, so I would appreciate your time! What do you think is the best approach?

**Comment by bqpd** [comment]
I think the problem is actually this error message ([from here](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_gplibrary_PR/75/buildnode=macys,optimizer=cvxopt/testReport/junit/gpkit.tests.from_paths/TestFiles/test_gpkitmodels_SP_SimPleAC_SimPleAC_mission_py_cvxopt/))

```
SP is not converging! Last GP iteration had a higher cost (3e+03) than the previous one (2.7e+03). Results for each iteration are in (Model).program.results. If your model contains SignomialEqualities, note that convergence is not guaranteed: try replacing any SigEqs you can and solving again.
```

The unbounded warning occurs in a cycle of feasibility solves, after some variable goes to 0/inf.

**Comment by bqpd** [comment]
It looks like the new model just doesn't solve with cvxopt. Because gpkitmodels are currently the only ones that otherwise do, I'd like to keep it that way...maybe add a `from gpkit import settings; if settings["default_solver"] == "cvxopt":  return`?

**Comment by 1ozturkbe** [comment]
That's what I thought. I guess I'll add that.

**Comment by 1ozturkbe** [comment]
test models please

**Comment by 1ozturkbe** [comment]
oy, now gassolar and jho are giving issues, probably because of the PR that they are waiting for. When you are ready @bqpd please merge.

**Comment by bqpd** [comment]
sorry for the late response! which PRs?

**Comment by 1ozturkbe** [comment]
The models are raising KeyErrors only when they are solved with mosek, likely because the signomial models (jho, solar etc.) have exceptions that make them not solve with cvxopt.

**Comment by 1ozturkbe** [comment]
gassolar at a minimum as a skipsolvers for cvxopt, which is the only reason it passes for cvxopt. I'm trying to find the exact line of failure rn.

**Comment by bqpd** [comment]
test models please

**Comment by 1ozturkbe** [comment]
It's an issue with varkeys [here](https://github.com/convexengineering/gassolar/blob/master/gassolar/gas/gas.py). Mission.Loiter.t is not valid apparently.

**Comment by bqpd** [comment]
those KeyErrors should be fixed, since the last PR test passed models...

**Comment by bqpd** [comment]
retesting to confirm this is still active

**Comment by 1ozturkbe** [comment]
huh, funny... let's see.

**Comment by bqpd** [comment]
looks like they're passing!

**Comment by 1ozturkbe** [comment]
yey! Let's wait for the last, and merge!

**Pull request merged**
